FROM registry.fedoraproject.org/fedora-toolbox:40

# Add your custom commands here to install software or configure the container

# Utilities
RUN sudo dnf update -y && \
    sudo dnf install -y \
      direnv \
      gcc \
      git \
      htop \
      just \
      make \
      opentofu \
      stow

# Languages and Package Managers
RUN sudo dnf update -y && \
    sudo dnf install -y \
      python3 \
      python3-pip \
      python3-virtualenv \
      nodejs \
      rust \
      cargo \
      golang \
      luarocks \
      ruby-devel \
      rubygems \
      rubygem-bundler \
      composer \
      php \
      julia

# Developer utils
RUN sudo dnf update -y && \
    sudo dnf install -y \
      ripgrep

RUN sudo dnf clean all

RUN pip install \
      aider-chat[chat] \
      ansible

# Play wright installation
RUN pip install \
      playwright

RUN cd /tmp && \
    wget https://github.com/neovim/neovim/releases/download/v0.11.1/nvim-linux-x86_64.tar.gz && \
    tar -xzf /tmp/nvim-linux-x86_64.tar.gz -C /opt && \
    rm -f /tmp/nvim*

ENV PATH="/opt/nvim-linux-x86_64/bin:${PATH}"
