- name: openai/gpt-5
  edit_format: diff
  weak_model_name: openai/gpt-5-nano
  use_repo_map: true
  use_temperature: false
  accepts_settings:
    - reasoning_effort

- name: azure/gpt-5-nano
  edit_format: diff
  weak_model_name: azure/gpt-5-nano
  use_repo_map: true
  use_temperature: false
  accepts_settings:
    - reasoning_effort
